site_name: TinyMotion Backend

theme:
  name: "material"

plugins:
  - search
  - mermaid2
  - gen-files:
      scripts:
        - scripts/gen_api_docs.py
  - redoc-tag

markdown_extensions:
  - mkdocs-click
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

nav:
  - "Overview": "index.md"
  - "Architecture": "architecture.md"
  - "Tutorials":
    - "Creating a user via the command line interface": "tutorials/creating-users-via-cli.md"
  - "Reference":
#    - "API Reference": "api.md"
    - "CLI Reference": "reference/cli.md"
