"""initialise database

Revision ID: 2fca15ca30b4
Revises: 
Create Date: 2024-04-09 06:51:25.636924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2fca15ca30b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('access_key', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_access_key'), ['access_key'], unique=True)

    op.create_table('infant',
    sa.Column('infant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('full_name', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('nhi_number', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('birth_date', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('due_date', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('infant_id')
    )
    with op.batch_alter_table('infant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infant_nhi_number'), ['nhi_number'], unique=True)

    op.create_table('consent',
    sa.Column('consent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('infant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('consent_giver_name', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('consent_giver_email', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('collected_physically', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['infant_id'], ['infant.infant_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_table('video',
    sa.Column('video_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256sum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('infant_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('video_size', sa.Integer(), nullable=True),
    sa.Column('sha256sum_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['infant_id'], ['infant.infant_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_video_name'), ['video_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_video_name'))

    op.drop_table('video')
    op.drop_table('consent')
    with op.batch_alter_table('infant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infant_nhi_number'))

    op.drop_table('infant')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_access_key'))

    op.drop_table('user')
    # ### end Alembic commands ###
