"""initialise

Revision ID: 6a9b437831d7
Revises: 
Create Date: 2024-02-18 15:59:18.117927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a9b437831d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infant',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('nhi_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('infant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('infant_id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('access_key')
    )
    op.create_table('consent',
    sa.Column('consent_giver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('infant_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['infant_id'], ['infant.infant_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_table('video',
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256sum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('infant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['infant_id'], ['infant.infant_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('consent')
    op.drop_table('user')
    op.drop_table('infant')
    # ### end Alembic commands ###
