"""add unique constraint on infant nhi_number

Revision ID: 7e4e5ac803ca
Revises: 6a9b437831d7
Create Date: 2024-02-22 08:29:51.748263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e4e5ac803ca'
down_revision: Union[str, None] = '6a9b437831d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infant', schema=None) as batch_op:
        batch_op.create_unique_constraint('infant_nhi_number_unique_constraint', ['nhi_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infant', schema=None) as batch_op:
        batch_op.drop_constraint('infant_nhi_number_unique_constraint', type_='unique')

    # ### end Alembic commands ###
