#!/bin/bash -e

# in case it is set already, it interferes with infisical login
unset INFISICAL_TOKEN

# TODO: only if not already logged in? (is there are way to tell?)
infisical login

# run tinymotion backend with secrets injected
infisical run --path /tinymotion_backend/app -- tinymotion-backend "$@"
