#!/bin/bash

set -e

# in case it is set already, it interferes with infisical login
unset INFISICAL_TOKEN

# login to infisical if needed
# at time of writing "infisical token" will return nonzero exit status if the
# user is not currently logged and zero if logged in
if ! infisical token >& /dev/null; then
    # user is not logged in already
    infisical login
fi

# run tinymotion backend with secrets injected
infisical run --env ${INFISICAL_ENV} --path /tinymotion_backend/app -- tinymotion-backend "$@"
