---
# duckdns domain and token should be set in infisical
use_duckdns: true

# docker image tag
tinymotion_image_tag: latest

# docker image pull policy
pull_policy: missing

# directory to restore database and video files from
restore_dir: restore
